version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.IdentityModel.Tokens
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: System.IdentityModel.Tokens.Jwt
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: EntityFrameworkCoreMock.Moq
    versions:
    - 2.0.0.107
    - 2.0.0.110
  - dependency-name: Microsoft.AspNetCore.Identity.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.SQLite
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.msbuild
    versions:
    - 3.0.2
  - dependency-name: Moq
    versions:
    - 4.16.0
  - dependency-name: AutoMapper.Extensions.Microsoft.DependencyInjection
    versions:
    - 8.1.0
